/**
 * LifeLog Integration for choreo-your-AI-work-journal
 * 
 * Add wellness tracking and $LIFE token rewards to your app.
 * Generated by LifeLog Distribution Agent
 * 
 * Installation: npm install @lifelog/sdk
 */

import { LifeLog } from '@lifelog/sdk';

// Initialize LifeLog client
const lifelog = new LifeLog({
  apiKey: process.env.LIFELOG_API_KEY,
  debug: process.env.NODE_ENV === 'development',
});

// === Productivity Tracking ===

/**
 * Log when a task is completed
 */
export async function onTaskComplete(task: { id: string; title: string; duration?: number }) {
  await lifelog.checkIn({
    message: `Completed task: ${task.title}`,
    category: 'productivity',
    duration: task.duration || 30,
    metadata: { taskId: task.id },
  });
}

/**
 * Track daily productivity goal
 */
export async function updateProductivityGoal(minutesWorked: number, targetMinutes: number = 240) {
  const result = await lifelog.trackGoal({
    name: 'Daily Focus Time',
    progress: minutesWorked,
    total: targetMinutes,
    unit: 'minutes',
    category: 'productivity',
  });
  
  if (result.completed) {
    console.log(`🎉 Goal complete! Earned ${result.reward} $LIFE`);
  }
  
  return result;
}

/**
 * Log a Pomodoro/focus session
 */
export async function logFocusSession(sessionMinutes: number, taskDescription?: string) {
  await lifelog.logActivity({
    type: 'end_session',
    name: 'focus_session',
    duration: sessionMinutes,
    metadata: { task: taskDescription },
  });
}

/**
 * Log a break (wellness reminder)
 */
export async function logBreak(breakMinutes: number) {
  await lifelog.checkIn({
    message: 'Taking a healthy break',
    category: 'wellness',
    duration: breakMinutes,
  });
}


// === Utility Functions ===

/**
 * Get current streaks
 */
export async function getStreaks() {
  return await lifelog.getStreaks();
}

/**
 * Get $LIFE token balance
 */
export async function getTokenBalance(walletAddress?: string) {
  return await lifelog.getTokenBalance(walletAddress);
}

/**
 * Get daily insight
 */
export async function getDailyInsight(date?: string) {
  return await lifelog.getDailyInsight(date);
}

/**
 * Export local data
 */
export function exportData() {
  return lifelog.exportLocalData();
}

// Export the client for advanced usage
export { lifelog };
